### ISSUE TITLE
G_loss will be negative value when I am training the model

### ISSUE THREAD

**Issue by chenfangyi1988** [hyunjin72/GraphGAN-PyTorch#1]
When I tried to train this model,  I found the G_loss will be negative. Why will this happen?
![image](https://user-images.githubusercontent.com/45649138/197342012-bcc01aaa-fcbb-43e2-97f9-bddcdce33f34.png)

**Comment by hyunjin72** [comment]
Hi, I have just fixed the code and the generator loss seems to work fine now.
I missed adding minus in g_loss when uploading the code.
Thank you for your comment :) 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/98798316/197373430-1e1ddf2a-1318-4647-9c74-a3cf65343b54.png">
